apply plugin: 'com.android.application'

android {
    namespace 'com.example.calculatorore'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.calculatorore"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.core:core:1.10.1'
}
